---
- name: configure applications
  hosts: machines_to_build
  become: yes
  tasks:
  #
  - name: add yum config
    ansible.builtin.copy: 
      src: "./repo1-rhel{{ ansible_distribution_major_version }}.repo"
      dest: /etc/yum.repos.d/

  - name: install a web server
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: add web content
    ansible.builtin.copy: 
      src: "./red_fish_{{ ansible_distribution_major_version }}.jpg"
      dest: /var/www/html/

  - name: add customized web content
    ansible.builtin.template: 
      src: ./index.html.j2
      dest: /var/www/html/index.html

  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes

