---
- name: configure applications
  hosts: machines_to_build
  become: yes
  tasks:
  #
  - name: add yum config
    ansible.builtin.copy: 
      src: "./repo1-rhel{{ ansible_distribution_major_version }}.repo"
      dest: /etc/yum.repos.d/

  - name: install a web server
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes

  - name: add web content
    ansible.builtin.copy: 
      src: "{{ item }}"
      dest: /var/www/html/
    loop:
    - ./Sebastes_mentella.jpg
    - ./index.html

