# check
#
- name: read system memory
  uri:
    url: "{{ web_ui }}/redfish/v1/Systems/1/Memory/proc1dimm2"
    method: GET
    headers:
      Accept: application/json
      OData-Version: "4.0"
      X-Auth-Token: "{{ session_token }}"
    body_format: json
    body: '{}'
    validate_certs: no
  register: r_memory
  no_log: "{{ toggle_no_log | default(true) }}"

- name: display the reply
  debug:
    verbosity: 1
    var: r_memory

- name: copy memory value
  set_fact:
    dimm2_size: "{{ r_memory.json.CapacityMiB }}"

- name: display memory capacity
  debug:
    var: dimm2_size

- name: pause to read message
  pause:
    seconds: 5
  when: "toggle_pause | default(false)"

- name: continue if this DIMM is at least 4GiB
  fail:
  when: "dimm2_size | int < 4096"

